const ActionType = {
  SET_USERINFO: 'SET_USERINFO',
  DELETE_USERINFO: 'DELETE_USERINFO',
  SET_ROOMCHAT: 'SET_ROOMCHAT',
  DELETE_ROOMCHAT: 'DELETE_ROOMCHAT',
  SHOW_STARTCHAT: 'SHOW_STARTCHAT',
  HIDE_STARTCHAT: 'HIDE_STARTCHAT',
  SET_FRIENDLIST: 'SET_FRIENDLIST',
}
export default ActionType
